project_id = "bcisbkompyqtfrtzccit"

[functions.import-wiki-feats]
verify_jwt = false

[functions.validate-feat]
verify_jwt = false

[functions.regenerate-description]
verify_jwt = false

[functions.check-wiki-redirects]
verify_jwt = false