project_id = "bcisbkompyqtfrtzccit"

[functions.validate-feat]
verify_jwt = false

[functions.generate-character-details]
verify_jwt = false

[functions.generate-character-portrait]
verify_jwt = false

[functions.generate-portrait-preview]
verify_jwt = false

