// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { journal } from '@/lib/localStore';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// §5.5 Instrumented fetch: per-URL timeouts + Date-header EWMA + journal.
// Without a timeout, one hung request wedges the entire sync mutex (ST-03/ST-04).
const REST_TIMEOUT_MS = 30_000;
const AUTH_TIMEOUT_MS = 15_000;

function timeoutFor(url: string): number | null {
  if (url.includes("/rest/v1/")) return REST_TIMEOUT_MS;
  if (url.includes("/auth/v1/")) return AUTH_TIMEOUT_MS;
  return null; // storage uploads & edge functions manage their own time
}

// §2.4 server clock offset EWMA — detects stale-response cache hits.
let _serverClockOffsetMs: number | null = null;
export function getServerClockOffsetMs() { return _serverClockOffsetMs; }
let _lastStaleAt = 0;
export function getLastStaleAt() { return _lastStaleAt; }

function shortPath(url: string): string {
  try { return new URL(url).pathname; } catch { return url; }
}

const instrumentedFetch: typeof fetch = async (input, init) => {
  const url = String(typeof input === "string" ? input : (input as Request).url);
  const ms = timeoutFor(url);
  const ctrl = new AbortController();
  const timer = ms
    ? setTimeout(() => ctrl.abort(new DOMException("sync-timeout", "TimeoutError")), ms)
    : null;
  const upstream = init?.signal;
  if (upstream) {
    if (upstream.aborted) ctrl.abort((upstream as any).reason);
    else upstream.addEventListener("abort", () => ctrl.abort((upstream as any).reason), { once: true });
  }
  const started = Date.now();
  try {
    const res = await fetch(input, { ...init, signal: ctrl.signal });
    const elapsed = Date.now() - started;
    // §2.4: Date-header EWMA for GETs; deviation > 2min means SW cache hit.
    try {
      if ((init?.method ?? "GET").toUpperCase() === "GET" && url.includes("/rest/v1/")) {
        const dh = res.headers.get("date");
        if (dh) {
          const delta = new Date(dh).getTime() - Date.now();
          if (_serverClockOffsetMs === null) _serverClockOffsetMs = delta;
          else _serverClockOffsetMs = Math.round(_serverClockOffsetMs * 0.8 + delta * 0.2);
          if (Math.abs(delta - _serverClockOffsetMs) > 120_000) {
            _lastStaleAt = Date.now();
            journal({ op: "stale-response", msg: shortPath(url), ok: false });
          }
        }
      }
    } catch {}
    if (!res.ok && (url.includes("/rest/v1/") || url.includes("/auth/v1/"))) {
      journal({ op: "fetch", msg: shortPath(url), status: res.status, ms: elapsed, ok: false });
    }
    return res;
  } catch (e: any) {
    const elapsed = Date.now() - started;
    if (url.includes("/rest/v1/") || url.includes("/auth/v1/")) {
      journal({ op: "fetch", msg: shortPath(url), ms: elapsed, ok: false, code: e?.name, ...(e?.message ? { msg: `${shortPath(url)}: ${e.message}` } : {}) });
    }
    throw e;
  } finally {
    if (timer) clearTimeout(timer);
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: { fetch: instrumentedFetch },
});
